terminate called after throwing an instance of 'std::bad_array_new_length'
  what():  std::bad_array_new_length
/var/spool/torque/mom_priv/jobs/1397854.polyp1.ie.lehigh.edu.SC: line 4:   976 Aborted                 ../Release/vws ${INPUT_FOLDER} ${OUTPUT_FILE} ${MAX_TIME} ${GENERATOR} ${TERMS} ${MIP_SOLVER} ${PROVIDE_PRIMAL_BOUND}
