
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/sek519/miniconda/lib/python3.9/site-packages/conda/cli/main.py", line 142, in main
        from ..activate import main as activator_main
      File "/home/sek519/miniconda/lib/python3.9/site-packages/conda/activate.py", line 22, in <module>
        from .base.context import ROOT_ENV_NAME, context, locate_prefix_by_name
      File "/home/sek519/miniconda/lib/python3.9/site-packages/conda/base/context.py", line 12, in <module>
        import platform
      File "/home/sek519/miniconda/lib/python3.9/platform.py", line 119, in <module>
        import subprocess
      File "/home/sek519/miniconda/lib/python3.9/subprocess.py", line 53, in <module>
        import contextlib
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 925, in _find_spec
      File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
      File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
      File "<frozen importlib._bootstrap_external>", line 1526, in find_spec
      File "<frozen importlib._bootstrap_external>", line 1569, in _fill_cache
    OSError: [Errno 5] Input/output error: '/home/sek519/warm_starting/vws/experiments'

`$ /home/sek519/miniconda/bin/conda shell.posix activate`

  environment variables:
                 CIO_TEST=<not set>
                CLASSPATH=/usr/local/xpress/lib/xprb.jar:/usr/local/xpress/lib/xprm.jar:.
        CONDA_DEFAULT_ENV=vws
                CONDA_EXE=/home/sek519/miniconda/bin/conda
                CONDA_LIB=/home/sek519/miniconda/envs/vws/lib/
             CONDA_PREFIX=/home/sek519/miniconda/envs/vws
           CONDA_PREFIX_1=/home/sek519/miniconda
    CONDA_PROMPT_MODIFIER=(vws)
         CONDA_PYTHON_EXE=/home/sek519/miniconda/bin/python
               CONDA_ROOT=/home/sek519/miniconda
              CONDA_SHLVL=2
           CURL_CA_BUNDLE=<not set>
          LD_LIBRARY_PATH=/home/sek519/warm_starting/vpc/lib/Cbc-trunk/buildg/lib:/home/sek519/g
                          urobi1003/linux64/lib:/usr/local/xpress/lib:/usr/local/mosek/8/tools/p
                          latform/linux64x86/bin:/usr/local/gurobi/linux64/lib:/usr/local/coinal
                          l/1.8/lib:/root/.mujoco/mjpro150/bin:/home/sek519/miniconda/envs/vws/l
                          ib/
                  MANPATH=/opt/moab/share/man::/usr/local/porta/man
               MODULEPATH=/etc/environment-modules/modules:/usr/share/modules/versions:/usr/Modu
                          les/$MODULE_VERSION/modulefiles:/usr/share/modules/modulefiles
                     PATH=/home/sek519/miniconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/gam
                          es:/usr/games
               PBS_O_PATH=/home/sek519/miniconda/envs/vws/bin:/home/sek519/miniconda/condabin:/h
                          ome/sek519/gurobi1003/linux64/bin:/usr/local/maui/bin:/opt/moab/bin:/u
                          sr/local/xpress/bin:/usr/local/mosek/8/tools/platform/linux64x86/bin:/
                          usr/local/gams:/opt/spark-3.0.0-bin-hadoop3.2/bin:/usr/local/bin:/usr/
                          bin:/bin:/usr/local/games:/usr/games:/usr/local/minos/5.5.1/bin:/usr/l
                          ocal/cplex/bin/x86-64_linux:/usr/local/coinall/1.8/bin:/usr/local/ampl
                          :/usr/local/porta/bin:/usr/local/matlab/latest/bin:/usr/local/sdpa-
                          gmp/sdpa-gmp-7.1.2:/usr/local/gurobi/linux64/bin:/home/software/soplex
                          -3.1.1/build/bin:/usr/local/cola_all/bin
               PYTHONPATH=/home/software/lib/python2.7/site-
                          packages::/home/software/lib/python2.6/dist-packages
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : vws
    active env location : /home/sek519/miniconda/envs/vws
            shell level : 2
       user config file : /home/sek519/.condarc
 populated config files : 
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.9.18.final.0
       virtual packages : __linux=4.9.0=0
                          __glibc=2.24=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/sek519/miniconda  (writable)
      conda av data dir : /home/sek519/miniconda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/sek519/miniconda/pkgs
                          /home/sek519/.conda/pkgs
       envs directories : /home/sek519/miniconda/envs
                          /home/sek519/.conda/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.31.0 CPython/3.9.18 Linux/4.9.0-18-amd64 debian/9.13 glibc/2.24
                UID:GID : 1312:1530
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

