Traceback (most recent call last):
  File "/home/sek519/miniconda/lib/python3.9/site-packages/conda/cli/main.py", line 142, in main
    from ..activate import main as activator_main
  File "/home/sek519/miniconda/lib/python3.9/site-packages/conda/activate.py", line 14, in <module>
    from textwrap import dedent
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1526, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1569, in _fill_cache
OSError: [Errno 5] Input/output error: '/home/sek519/warm_starting/vws/experiments'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sek519/miniconda/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/home/sek519/miniconda/lib/python3.9/site-packages/conda/cli/main.py", line 150, in main
    init_loggers()
  File "/home/sek519/miniconda/lib/python3.9/site-packages/conda/cli/main.py", line 56, in init_loggers
    from ..gateways.logging import initialize_logging, set_verbosity, set_file_logging
  File "/home/sek519/miniconda/lib/python3.9/site-packages/conda/gateways/logging.py", line 15, in <module>
    from ..common.io import attach_stderr_handler, _FORMATTER
  File "/home/sek519/miniconda/lib/python3.9/site-packages/conda/common/io.py", line 7, in <module>
    from concurrent.futures import ProcessPoolExecutor, ThreadPoolExecutor, Executor, Future, _base, as_completed  # NOQA
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "/home/sek519/miniconda/lib/python3.9/concurrent/futures/__init__.py", line 44, in __getattr__
    from .process import ProcessPoolExecutor as pe
  File "/home/sek519/miniconda/lib/python3.9/concurrent/futures/process.py", line 51, in <module>
    import multiprocessing as mp
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1526, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1569, in _fill_cache
OSError: [Errno 5] Input/output error: '/home/sek519/warm_starting/vws/experiments'
