Error in usercustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 5] Input/output error: '/home/sek519/warm_starting/vws/experiments'
