Error processing line 1 of /home/sek519/miniconda/lib/python3.9/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "/home/sek519/miniconda/lib/python3.9/site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
    File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 925, in _find_spec
    File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
    File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
    File "<frozen importlib._bootstrap_external>", line 1526, in find_spec
    File "<frozen importlib._bootstrap_external>", line 1569, in _fill_cache
  OSError: [Errno 5] Input/output error: '/home/sek519/warm_starting/vws/experiments'

Remainder of file ignored
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
/var/spool/torque/mom_priv/jobs/1797339.polyp1.ie.lehigh.edu.SC: line 4: 31850 Aborted                 ../Release/vws ${INPUT_FOLDER} ${OUTPUT_FILE} ${MAX_TIME} ${GENERATOR} ${TERMS} ${MIP_SOLVER} ${PROVIDE_PRIMAL_BOUND} ${SEED_INDEX}
