terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc


ERROR while running Cbc. Signal SIGABRT caught. Getting stack trace.


ERROR while running Cbc. Signal SIGSEGV caught. Getting stack trace.
/var/spool/torque/mom_priv/jobs/1220377.polyp1.ie.lehigh.edu.SC: line 4: 12864 Segmentation fault      ../Debug/vws ${INPUT_FOLDER} ${OUTPUT_FILE} ${MAX_TIME} ${GENERATOR} ${TERMS}
